In [2]:
import pandas as pd
import numpy as np 
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import sklearn 
import seaborn as sb

In [3]:
df= pd.read_csv("df_localidad.csv")
df.describe()

,Unnamed: 0,precipitacion,mes,idProvincia,idDepartamento,Sup_Sembrada,Sup_Cosechada,Producción,Rendimiento
count,16267.000000,15826.000000,15826.000000,16267.0,16267.000000,16267.000000,16267.000000,16267.000000,16267.000000
mean,131126.799717,91.077170,6.518135,6.0,497.307678,24853.127866,24018.227700,84238.144833,3402.522592
std,75611.733721,75.881012,3.453974,0.0,166.709255,34029.569101,33753.325603,118680.208741,2061.488472
min,29.000000,0.000000,1.000000,6.0,210.000000,15.000000,0.000000,0.000000,0.000000
25%,64453.000000,33.600000,4.000000,6.0,413.000000,1000.000000,650.000000,1800.000000,2078.000000
50%,129220.000000,71.000000,7.000000,6.0,469.000000,12000.000000,10250.000000,29400.000000,2839.000000
75%,196595.500000,130.200000,10.000000,6.0,686.000000,33360.000000,32000.000000,122000.000000,4100.000000
max,263830.000000,355.600000,12.000000,6.0,714.000000,215282.000000,211482.000000,744137.000000,13886.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16267 entries, 0 to 16266
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      16267 non-null  int64
 1   precipitacion   15826 non-null  float64
 2   Campaña         16267 non-null  object
 3   mes             15826 non-null  float64
 4   Cultivo         16267 non-null  object
 5   idProvincia     16267 non-null  int64
 6   idDepartamento  16267 non-null  int64
 7   Sup_Sembrada    16267 non-null  int64
 8   Sup_Cosechada   16267 non-null  float64
 9   Producción      16267 non-null  float64
 10  Rendimiento     16267 non-null  float64
dtypes: float64(5), int64(4), object(2)
memory usage: 1.4+ MB

In [4]:
df.sample(50)

,Unnamed: 0,precipitacion,Campaña,mes,Cultivo,idProvincia,idDepartamento,Sup_Sembrada,Sup_Cosechada,Producción,Rendimiento
15414,249931,130.8,2013/14,5.0,Trigo total,6,462,8000,8000.0,28800.0,3600.0
2504,42090,137.9,1992/93,3.0,Soja total,6,413,62200,56400.0,91700.0,1626.0
14326,231470,307.0,2012/13,10.0,Sorgo,6,210,900,600.0,3600.0,6000.0
143,2549,54.7,1987/88,4.0,Avena,6,462,5500,0.0,0.0,0.0
12423,200079,312.3,2009/10,12.0,Sorgo,6,469,700,700.0,4900.0,7000.0
15709,255005,231.0,2014/15,11.0,Avena,6,469,7000,1000.0,3000.0,3000.0
10635,171592,52.6,2006/07,5.0,Soja total,6,210,104200,104200.0,393220.0,3774.0
796,14719,35.5,1989/90,8.0,Soja total,6,686,52000,52000.0,124800.0,2400.0
5753,91571,169.3,1998/99,3.0,Girasol,6,462,10000,10000.0,21000.0,2100.0
15926,258482,NaN,2021/22,NaN,Girasol,6,469,3800,3800.0,8550.0,2250.0
4937,78485,34.1,1997/98,9.0,Avena,6,210,2600,780.0,1600.0,2051.0
5498,87616,21.3,1998/99,9.0,Soja total,6,714,81000,81000.0,250000.0,3086.0
13998,226069,122.0,2011/12,5.0,Avena,6,714,300,300.0,1050.0,3500.0
8829,141443,1.0,2003/04,6.0,Soja 1ra,6,462,46000,46000.0,144900.0,3150.0
15055,243552,195.2,2013/14,11.0,Girasol,6,469,3150,3150.0,8190.0,2600.0
2327,39707,90.6,1992/93,12.0,Cebada cervecera,6,462,1500,1500.0,3600.0,2400.0
10020,161387,46.0,2005/06,6.0,Avena,6,413,1500,300.0,720.0,2400.0
7893,125317,187.0,2002/03,10.0,Soja total,6,413,80000,79800.0,243000.0,3045.0
3065,49837,11.9,1993/94,3.0,Trigo total,6,210,28500,28300.0,50900.0,1799.0
11031,177975,80.4,2007/08,12.0,Sorgo,6,413,400,400.0,2600.0,6500.0
9148,146811,229.7,2004/05,12.0,Trigo total,6,714,16700,16700.0,56780.0,3400.0
10218,164656,31.0,2006/07,9.0,Sorgo,6,413,200,200.0,1200.0,6000.0
8805,140951,93.5,2003/04,5.0,Trigo total,6,686,19500,19500.0,68250.0,3500.0
227,4034,0.5,1987/88,5.0,Trigo total,6,469,26000,25400.0,43700.0,1720.0
6449,102428,23.0,1999/00,6.0,Soja total,6,210,67700,67000.0,139200.0,2078.0
9013,144604,66.2,2004/05,10.0,Girasol,6,714,800,800.0,2000.0,2500.0
2495,41922,137.9,1992/93,3.0,Lino,6,413,200,200.0,200.0,1000.0
11168,180188,177.5,2007/08,3.0,Girasol,6,210,200,200.0,760.0,3800.0
3844,61209,12.0,1995/96,9.0,Cebada cervecera,6,210,500,500.0,1300.0,2600.0
3043,49485,11.9,1993/94,3.0,Girasol,6,210,500,500.0,1100.0,2200.0
9718,156319,45.9,2005/06,12.0,Cebada cervecera,6,714,250,250.0,800.0,3200.0
12224,196975,145.1,2009/10,9.0,Maíz,6,462,14000,13000.0,143000.0,11000.0
11923,192225,112.7,2008/09,4.0,Girasol,6,210,200,200.0,400.0,2000.0
4747,75281,70.8,1996/97,4.0,Soja total,6,210,74000,73400.0,184800.0,2518.0
4738,75045,70.8,1996/97,4.0,Girasol,6,469,36000,29000.0,53700.0,1852.0
501,9150,82.8,1988/89,12.0,Trigo total,6,210,24500,24500.0,61250.0,2500.0
7412,117581,115.2,2001/02,1.0,Avena,6,469,8000,1100.0,1320.0,1200.0
14529,234730,84.0,2012/13,2.0,Cebada cervecera,6,714,350,350.0,980.0,2800.0
11885,191619,35.5,2008/09,3.0,Soja 2da,6,469,34500,29325.0,21994.0,750.0
14272,230611,90.0,2012/13,9.0,Trigo total,6,210,16000,16000.0,56000.0,3500.0
11912,192069,112.7,2008/09,4.0,Cebada cervecera,6,210,3000,2900.0,8410.0,2900.0
9437,151697,7.4,2004/05,6.0,Soja total,6,714,94521,94521.0,304660.0,3223.0
3747,59788,18.1,1994/95,7.0,Avena,6,686,3000,150.0,300.0,2000.0
1019,18725,122.9,1989/90,2.0,Girasol,6,413,12000,12000.0,19200.0,1600.0
1247,22820,29.8,1990/91,8.0,Cebada cervecera,6,462,2000,2000.0,5200.0,2600.0
4611,72874,189.8,1996/97,1.0,Girasol,6,714,5000,5000.0,10500.0,2100.0
6798,107854,279.3,2000/01,1.0,Girasol,6,469,5400,5000.0,11000.0,2200.0
757,13975,31.3,1988/89,7.0,Soja total,6,714,72000,72000.0,125000.0,1736.0
6147,97754,54.2,1999/00,12.0,Avena,6,469,12000,1500.0,2250.0,1500.0
9726,156515,45.9,2005/06,12.0,Maíz,6,469,18000,15000.0,121500.0,8100.0

In [6]:
#borramos los datos NaN
df.dropna(inplace=True)

In [5]:
del df['Unnamed: 0']

In [7]:
#def Rendimiento(Rendimiento:str) -> int:
    """
    This function encodes the rendimiento variable.
    """
    
    if Rendimiento >= 3500: return 1
    else: return 0

IndentationError: unexpected indent (3105436021.py, line 2)

In [ ]:
# Se aplica la funcion a la columna Rendimiento
#df["Rendimiento"] = df["Rendimiento"].apply(Rendimiento)

In [ ]:
df

In [8]:
#cambiamos rendimiento por Target que es lo que buscamos predecir
df["target"] = df["Rendimiento"]

In [9]:
df.sample(50)

,precipitacion,Campaña,mes,Cultivo,idProvincia,idDepartamento,Sup_Sembrada,Sup_Cosechada,Producción,Rendimiento,target
13464,29.0,2010/11,7.0,Maíz,6,462,16100,15100.0,131280.0,8694.0,8694.0
1312,176.0,1990/91,10.0,Girasol,6,413,10600,10600.0,19100.0,1802.0,1802.0
14032,122.0,2011/12,5.0,Soja total,6,462,124200,122400.0,340940.0,2785.0,2785.0
14340,167.0,2012/13,11.0,Avena,6,462,3000,210.0,440.0,2095.0,2095.0
11441,3.0,2008/09,8.0,Cebada cervecera,6,413,14000,13500.0,45900.0,3400.0,3400.0
3428,122.0,1994/95,12.0,Avena,6,210,3600,180.0,324.0,1800.0,1800.0
11813,75.3,2008/09,2.0,Maíz,6,462,14000,12050.0,78570.0,6520.0,6520.0
3137,71.5,1993/94,5.0,Lino,6,686,20,20.0,10.0,500.0,500.0
6636,254.6,2000/01,10.0,Girasol,6,469,5400,5000.0,11000.0,2200.0,2200.0
12568,81.5,2009/10,3.0,Girasol,6,686,300,300.0,600.0,2000.0,2000.0
6481,1.8,1999/00,7.0,Colza,6,413,150,150.0,300.0,2000.0,2000.0
12147,14.3,2009/10,8.0,Avena,6,714,350,350.0,1015.0,2900.0,2900.0
2867,154.9,1993/94,11.0,Girasol,6,210,500,500.0,1100.0,2200.0,2200.0
7562,65.0,2001/02,4.0,Avena,6,469,8000,1100.0,1320.0,1200.0,1200.0
1550,47.2,1990/91,5.0,Trigo total,6,210,44000,44000.0,115000.0,2614.0,2614.0
1649,62.7,1991/92,8.0,Sorgo,6,210,200,200.0,800.0,4000.0,4000.0
8722,134.0,2003/04,4.0,Cebada cervecera,6,413,10200,10200.0,30600.0,3000.0,3000.0
6614,33.6,2000/01,9.0,Trigo total,6,413,40000,40000.0,120000.0,3000.0,3000.0
3421,48.5,1994/95,11.0,Trigo total,6,210,38000,38000.0,102600.0,2700.0,2700.0
1370,91.4,1990/91,12.0,Cebada cervecera,6,413,4700,4700.0,12700.0,2702.0,2702.0
9943,138.5,2005/06,4.0,Soja 2da,6,210,23500,23500.0,59550.0,2534.0,2534.0
10990,80.4,2007/08,12.0,Avena,6,686,1000,300.0,900.0,3000.0,3000.0
12558,81.5,2009/10,3.0,Cebada cervecera,6,686,500,500.0,2300.0,4600.0,4600.0
5304,93.3,1997/98,5.0,Girasol,6,210,4500,4500.0,6800.0,1511.0,1511.0
14071,10.5,2011/12,6.0,Maíz,6,686,23000,19000.0,125400.0,6600.0,6600.0
12710,88.4,2009/10,5.0,Sorgo,6,210,500,400.0,2200.0,5500.0,5500.0
1575,75.2,1990/91,6.0,Soja total,6,469,37000,33400.0,63400.0,1898.0,1898.0
1154,54.6,1989/90,5.0,Soja total,6,462,15000,15000.0,33000.0,2200.0,2200.0
7484,44.6,2001/02,2.0,Soja 1ra,6,413,32000,32000.0,102500.0,3203.0,3203.0
12472,162.0,2009/10,1.0,Soja total,6,210,120800,120800.0,453200.0,3752.0,3752.0
12900,119.0,2010/11,9.0,Cebada cervecera,6,413,6000,6000.0,32400.0,5400.0,5400.0
13061,49.4,2010/11,12.0,Avena,6,469,400,400.0,1360.0,3400.0,3400.0
336,2.0,1988/89,8.0,Girasol,6,714,1000,1000.0,2000.0,2000.0,2000.0
13599,45.8,2011/12,9.0,Sorgo,6,469,1130,1130.0,6770.0,5991.0,5991.0
15513,17.0,2013/14,7.0,Soja total,6,714,108000,107850.0,436995.0,4052.0,4052.0
1197,0.4,1989/90,6.0,Soja total,6,714,72000,72000.0,180000.0,2500.0,2500.0
4408,41.5,1996/97,8.0,Soja total,6,714,60500,60050.0,96800.0,1612.0,1612.0
8600,128.3,2003/04,1.0,Soja 1ra,6,469,34500,34400.0,113200.0,3291.0,3291.0
3604,94.4,1994/95,3.0,Trigo total,6,469,30000,30000.0,81000.0,2700.0,2700.0
14730,126.0,2012/13,5.0,Soja 1ra,6,462,66600,63300.0,215220.0,3400.0,3400.0
8341,98.1,2002/03,7.0,Trigo total,6,210,25000,25000.0,52500.0,2100.0,2100.0
12668,88.4,2009/10,5.0,Avena,6,686,1500,600.0,1680.0,2800.0,2800.0
12743,42.0,2009/10,6.0,Girasol,6,714,1000,1000.0,2900.0,2900.0,2900.0
12557,81.5,2009/10,3.0,Cebada cervecera,6,469,750,750.0,2480.0,3307.0,3307.0
6066,63.5,1999/00,10.0,Colza,6,210,50,50.0,100.0,2000.0,2000.0
12567,81.5,2009/10,3.0,Girasol,6,469,3900,3900.0,8580.0,2200.0,2200.0
7230,110.8,2001/02,9.0,Maíz,6,469,14000,11800.0,76700.0,6500.0,6500.0
1397,91.4,1990/91,12.0,Trigo total,6,462,14000,14000.0,34300.0,2450.0,2450.0
15338,188.3,2013/14,4.0,Soja 1ra,6,686,111900,110900.0,487960.0,4400.0,4400.0
1750,244.1,1991/92,12.0,Colza,6,469,800,800.0,1500.0,1875.0,1875.0

In [ ]:
#borramos la columna idProvincia ya que no aporta ningun dato relevante
del df["idProvincia"]

In [ ]:
#borramos  la columna de Rendimiento que no la reemplazo "target"
del df["Rendimiento"]

In [ ]:
#borramos las columnas categoricas de "campaña" y "cultivo"
del df["Campaña"]

In [ ]:
del df["Cultivo"]

In [ ]:
#Deep=true en el metodo Copy, signidica que quiero aplicar la data del DF originaly hacer cambios sin que esto afecte la data original
X = df.drop(columns=["target"]).copy(deep=True)

In [ ]:
X.sample(30)

In [ ]:
X.info()

In [ ]:
y= df["target"].copy(deep=True)

In [ ]:
y.sample(15)

In [ ]:
#Preparando la data para el training
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test =train_test_split(X,y, test_size=0.33, random_state=42)

In [ ]:
X_test.shape

In [1]:
#importamos algoritmos
from sklearn.neighbors import KNeighborsClassifier #KNN
from sklearn.linear_model import LogisticRegression #Regresion logistica
from sklearn.ensemble import RandomForestRegressorlassifier # Random Forest
from sklearn.tree import DecisionTreeRegressor

ImportError: cannot import name 'RandomForestRegressorlassifier' from 'sklearn.ensemble' (C:\Users\syluv\miniconda3\lib\site-packages\sklearn\ensemble\__init__.py)

In [ ]:
knn=KNeighborsClassifier() #neighbors = 5 (default)
lgr= LogisticRegression()
rfc= RandomForestClassifier() # trees=100 (Default)

In [ ]:
print(type(knn))
print(type(lgr))
print(type(rfc))

In [ ]:
#train Knn
knn.fit(X_train, y_train)

In [ ]:
#Predict whit KNN
knn.predict(X_test)

In [ ]:
y_test

In [ ]:
knn.score(X,y)

In [ ]:
#train logistic Regretion
lgr.fit(X_train, y_train)

In [ ]:
#predict whit logistic Reg
lgr.predict(X_test)

In [ ]:
lgr.score(X,y)

In [ ]:
#train random forest
rfc.fit(X_train, y_train)

In [ ]:
#Predict whit random forest
rfc.predict(X_test)

In [ ]:
rfc.score(X,y)