In [1]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

In [14]:
df_definitivo = pd.read_csv("Estimaciones (Provincia de BsAs 1987-2022).csv", encoding='latin-1', sep=";")
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitacion_Anual'] = '860' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitacion_Anual'] = '833,2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitacion_Anual '] = '1111,4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitacion_Anual '] = '1068,6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitacion_Anual'] = '897,4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitacion_Anual'] = '1309,8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitacion_Anual'] = '812' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitacion_Anual'] = '948,3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitacion_Anual'] = '653,7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitacion_Anual'] = '1020,2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitacion_Anual'] = '986,5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitacion_Anual'] = '821,4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitacion_Anual'] = '984,7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitacion_Anual'] = '1447,5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitacion_Anual'] = '1285,7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitacion_Anual'] = '1103,4'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitacion_Anual'] = '735,1' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitacion_Anual'] = '905' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitacion_Anual'] = '812,9' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitacion_Anual'] = '1237,4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitacion_Anual'] = '793,5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitacion_Anual'] = '520,6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitacion_Anual'] = '1396,3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitacion_Anual'] = '807,7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitacion_Anual'] = '982,5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitacion_Anual'] = '1282,4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitacion_Anual'] = '1215,9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Septiembre'] = '54.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Septiembre'] = '68.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Septiembre'] = '20.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Septiembre'] = '84.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Septiembre'] = '63.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Septiembre'] = '56.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Septiembre'] = '46.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Septiembre'] = '20.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Septiembre'] = '12.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Septiembre'] = '48.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Septiembre'] = '34.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Septiembre'] = '21.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Septiembre'] = '67.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Septiembre'] = '33.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Septiembre'] = '110.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Septiembre'] = '20.5'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Septiembre'] = '21.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Septiembre'] = '11.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Septiembre'] = '64.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Septiembre'] = '31.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Septiembre'] = '74.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Septiembre'] = '39.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Septiembre'] = '145.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Septiembre'] = '119.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Septiembre'] = '45.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Septiembre'] = '90.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Septiembre'] = '22.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '2014/15', 'Precipitaciones Septiembre'] = '89.5'
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Octubre'] = '128.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Octubre'] = '57' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Octubre'] = '46.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Octubre'] = '176' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Octubre'] = '161.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Octubre'] = '75.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Octubre'] = '179.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Octubre'] = '134.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Octubre'] = '111' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Octubre'] = '93.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Octubre'] = '146.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Octubre'] = '65.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Octubre'] = '63.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Octubre'] = '254.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Octubre'] = '264.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Octubre'] = '187'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Octubre'] = '86' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Octubre'] = '66.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Octubre'] = '35.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Octubre'] = "259.1"
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Octubre'] = '88.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Octubre'] = '89.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Octubre'] = '111.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Octubre'] = '62.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Octubre'] = '100' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Octubre'] = '307' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Octubre'] = '101.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2014/15', 'Precipitaciones Octubre'] = '140.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Noviembre'] = '117.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Noviembre'] = '36.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Noviembre'] = '46.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Noviembre'] = '193.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Noviembre'] = '90.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Noviembre'] = '145.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Noviembre'] = '154.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Noviembre'] = '48.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Noviembre'] = '55.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Noviembre'] = '198.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Noviembre'] = '82.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Noviembre'] = '118.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Noviembre'] = '47.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Noviembre'] = '122.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Noviembre'] = '134.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Noviembre'] = '149.0'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Noviembre'] = '126.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Noviembre'] = '111.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Noviembre'] = '119.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Noviembre'] = '67.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Noviembre'] = '109.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Noviembre'] = '63.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Noviembre'] = '203.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Noviembre'] = '8.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Noviembre'] = '131.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Noviembre'] = '167.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Noviembre'] = '195.2'
df_definitivo.loc[df_definitivo['Campaña'] == '2014/15', 'Precipitaciones Noviembre'] = '231.0'
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Diciembre'] = '118.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Diciembre'] = '82.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Diciembre'] = '193.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Diciembre'] = '91.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Diciembre'] = '244.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Diciembre'] = '90.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Diciembre'] = '109.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Diciembre'] = '122.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Diciembre'] = '69.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Diciembre'] = '195.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Diciembre'] = '202.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Diciembre'] = '130.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Diciembre'] = '54.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Diciembre'] = '14.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Diciembre'] = '83.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Diciembre'] = '169.0'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Diciembre'] = '71.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Diciembre'] = '229.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Diciembre'] = '45.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Diciembre'] = '141.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Diciembre'] = '80.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Diciembre'] = '47.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Diciembre'] = '312.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Diciembre'] = '49.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Diciembre'] = '1.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Diciembre'] = '150.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Diciembre'] = '61.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2014/15', 'Precipitaciones Diciembre'] = '157.0'
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Enero'] = '56.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Enero'] = '112.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Enero'] = '178.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Enero'] = '111.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Enero'] = '115.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Enero'] = '219.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Enero'] = '51.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Enero'] = '92.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Enero'] = '66.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Enero'] = '189.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Enero'] = '91.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Enero'] = '127.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Enero'] = '57.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Enero'] = '279.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Enero'] = '115.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Enero'] = '57.7'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Enero'] = '128.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Enero'] = '173.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Enero'] = '211.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Enero'] = '111.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Enero'] = '100.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Enero'] = '33.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Enero'] = '162.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Enero'] = '198.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Enero'] = '188.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Enero'] = '28.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Enero'] = '188.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Febrero'] = '32.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Febrero'] = '130.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Febrero'] = '122.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Febrero'] = '93.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Febrero'] = '15.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Febrero'] = '30.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Febrero'] = '29.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Febrero'] = '53.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Febrero'] = '103.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Febrero'] = '55.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Febrero'] = '169.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Febrero'] = '139.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Febrero'] = '134.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Febrero'] = '276.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Febrero'] = '44.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Febrero'] = '186.3'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Febrero'] = '20.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Febrero'] = '46.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Febrero'] = '91.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Febrero'] = '256.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Febrero'] = '161.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Febrero'] = '75.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Febrero'] = '246.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Febrero'] = '123.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Febrero'] = '233.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Febrero'] = '84.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Febrero'] = '210.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Marzo'] = '283.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Marzo'] = '174.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Marzo'] = '329.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Marzo'] = '115.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Marzo'] = '103.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Marzo'] = '137.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Marzo'] = '11.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Marzo'] = '94.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Marzo'] = '28.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Marzo'] = '77.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Marzo'] = '57.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Marzo'] = '169.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Marzo'] = '110.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Marzo'] = '321.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Marzo'] = '349.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Marzo'] = '134.0'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Marzo'] = '54.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Marzo'] = '149.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Marzo'] = '97.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Marzo'] = '267.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Marzo'] = '177.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Marzo'] = '35.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Marzo'] = '81.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Marzo'] = '88.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Marzo'] = '124.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Marzo'] = '279.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Marzo'] = '118.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Abril'] = '54.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Abril'] = '79.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Abril'] = '118.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Abril'] = '155.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Abril'] = '68.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Abril'] = '355.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Abril'] = '125.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Abril'] = '296.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Abril'] = '171.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Abril'] = '70.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Abril'] = '110.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Abril'] = '38.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Abril'] = '142.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Abril'] = '85.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Abril'] = '65.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Abril'] = '147.0'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Abril'] = '134.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Abril'] = '44.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Abril'] = '138.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Abril'] = '50.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Abril'] = '1.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Abril'] = '112.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Abril'] = '45.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Abril'] = '98.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Abril'] = '36.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Abril'] = '51.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Abril'] = '188.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Mayo'] = '0.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Mayo'] = '93.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Mayo'] = '54.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Mayo'] = '47.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Mayo'] = '35.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Mayo'] = '104.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Mayo'] = '71.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Mayo'] = '54.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Mayo'] = '35.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Mayo'] = '48.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Mayo'] = '93.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Mayo'] = '9.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Mayo'] = '307.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Mayo'] = '59.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Mayo'] = '118.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Mayo'] = '52.9'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Mayo'] = '93.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Mayo'] = '5.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Mayo'] = '9.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Mayo'] = '52.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Mayo'] = '0.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Mayo'] = '24.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Mayo'] = '88.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Mayo'] = '60.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Mayo'] = '122.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Mayo'] = '126.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Mayo'] = '130.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Junio'] = '11.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Junio'] = '49.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Junio'] = '0.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Junio'] = '75.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Junio'] = '51.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Junio'] = '109.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Junio'] = '74.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Junio'] = '19.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Junio'] = '1.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Junio'] = '69.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Junio'] = '3.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Junio'] = '16.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Junio'] = '23.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Junio'] = '17.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Junio'] = '3.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Junio'] = '19.1'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Junio'] = '1.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Junio'] = '7.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Junio'] = '46.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Junio'] = '16.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Junio'] = '26.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Junio'] = '3.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Junio'] = '42.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Junio'] = '31.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Junio'] = '10.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Junio'] = '18.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Junio'] = '64.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Julio'] = '36.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Julio'] = '31.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Julio'] = '32.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Julio'] = '32.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Julio'] = '14.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Julio'] = '3.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Julio'] = '36.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Julio'] = '18.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Julio'] = '12.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Julio'] = '12.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Julio'] = '36.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Julio'] = '14.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Julio'] = '1.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Julio'] = '18.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Julio'] = '17.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Julio'] = '98.1'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Julio'] = '44.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Julio'] = '40.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Julio'] = '23.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Julio'] = '3.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Julio'] = '36.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Julio'] = '114.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Julio'] = '38.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Julio'] = '29.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Julio'] = '1.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Julio'] = '40.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Julio'] = '17.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1987/88', 'Precipitaciones Agosto'] = '35.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1988/89', 'Precipitaciones Agosto'] = '2.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1989/90', 'Precipitaciones Agosto'] = '35.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1990/91', 'Precipitaciones Agosto'] = '29.8' 
df_definitivo.loc[df_definitivo['Campaña'] == '1991/92', 'Precipitaciones Agosto'] = '62.7' 
df_definitivo.loc[df_definitivo['Campaña'] == '1992/93', 'Precipitaciones Agosto'] = '93.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '1993/94', 'Precipitaciones Agosto'] = '30.4' 
df_definitivo.loc[df_definitivo['Campaña'] == '1994/95', 'Precipitaciones Agosto'] = '33.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '1995/96', 'Precipitaciones Agosto'] = '0.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '1996/97', 'Precipitaciones Agosto'] = '41.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '1997/98', 'Precipitaciones Agosto'] = '8.1' 
df_definitivo.loc[df_definitivo['Campaña'] == '1998/99', 'Precipitaciones Agosto'] = '9.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '1999/00', 'Precipitaciones Agosto'] = '34.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2000/01', 'Precipitaciones Agosto'] = '14.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2001/02', 'Precipitaciones Agosto'] = '135.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2002/03', 'Precipitaciones Agosto'] = '82.0'
df_definitivo.loc[df_definitivo['Campaña'] == '2003/04', 'Precipitaciones Agosto'] = '21.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2004/05', 'Precipitaciones Agosto'] = '67.5' 
df_definitivo.loc[df_definitivo['Campaña'] == '2005/06', 'Precipitaciones Agosto'] = '88.6' 
df_definitivo.loc[df_definitivo['Campaña'] == '2006/07', 'Precipitaciones Agosto'] = '0.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2007/08', 'Precipitaciones Agosto'] = '1.2' 
df_definitivo.loc[df_definitivo['Campaña'] == '2008/09', 'Precipitaciones Agosto'] = '3.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2009/10', 'Precipitaciones Agosto'] = '14.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2010/11', 'Precipitaciones Agosto'] = '2.3' 
df_definitivo.loc[df_definitivo['Campaña'] == '2011/12', 'Precipitaciones Agosto'] = '10.0' 
df_definitivo.loc[df_definitivo['Campaña'] == '2012/13', 'Precipitaciones Agosto'] = '131.9' 
df_definitivo.loc[df_definitivo['Campaña'] == '2013/14', 'Precipitaciones Agosto'] = '0.0' 
df_definitivo

,Cultivo,Campaña,Provincia,Departamento,idProvincia,idDepartamento,Sup. Sembrada,Sup. Cosechada,Producción,Rendimiento,...,Precipitaciones Noviembre,Precipitaciones Diciembre,Precipitaciones Enero,Precipitaciones Febrero,Precipitaciones Marzo,Precipitaciones Abril,Precipitaciones Mayo,Precipitaciones Junio,Precipitaciones Julio,Precipitaciones Agosto
0,Avena,1987/88,BUENOS AIRES,25 DE MAYO,6,854,3000,1000,1800,1800,...,117.0,118.5,56.2,32.9,283.0,54.7,0.5,11.6,36.5,35.4
1,Avena,1989/90,BUENOS AIRES,25 DE MAYO,6,854,2000,0,0,0,...,46.9,193.5,178.7,122.9,329.1,118.9,54.6,0.4,32.5,35.5
2,Avena,1992/93,BUENOS AIRES,25 DE MAYO,6,854,100,100,100,1000,...,145.6,90.6,219.5,30.7,137.9,355.6,104.3,109.8,3.3,93.2
3,Avena,1994/95,BUENOS AIRES,25 DE MAYO,6,854,500,500,800,1600,...,48.5,122.0,92.0,53.1,94.4,296.0,54.6,19.5,18.1,33.0
4,Avena,1995/96,BUENOS AIRES,25 DE MAYO,6,854,2000,500,1200,2400,...,55.7,69.0,66.8,103.9,28.1,171.3,35.6,1.0,12.2,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23448,Trigo total,2017/18,BUENOS AIRES,ZARATE,6,882,1950,1950,8385,4300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23449,Trigo total,2018/19,BUENOS AIRES,ZARATE,6,882,2800,2800,12320,4400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23450,Trigo total,2019/20,BUENOS AIRES,ZARATE,6,882,2500,2500,10000,4000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23451,Trigo total,2020/21,BUENOS AIRES,ZARATE,6,882,3000,3000,11700,3900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23452,Trigo total,2021/22,BUENOS AIRES,ZARATE,6,882,7552,7552,36250,4800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_definitivo.rename(columns={"Sup. Sembrada":"Sup_Sembrada","Sup. Cosechada":"Sup_Cosechada"}, inplace=True)

In [4]:
df_definitivo

,Cultivo,Campaña,Provincia,Departamento,idProvincia,idDepartamento,Sup_Sembrada,Sup_Cosechada,Producción,Rendimiento,...,Precipitaciones Noviembre,Precipitaciones Diciembre,Precipitaciones Enero,Precipitaciones Febrero,Precipitaciones Marzo,Precipitaciones Abril,Precipitaciones Mayo,Precipitaciones Junio,Precipitaciones Julio,Precipitaciones Agosto
0,Avena,1987/88,BUENOS AIRES,25 DE MAYO,6,854,3000,1000,1800,1800,...,117.0,118.5,56.2,32.9,283.0,54.7,0.5,11.6,36.5,35.4
1,Avena,1989/90,BUENOS AIRES,25 DE MAYO,6,854,2000,0,0,0,...,46.9,193.5,178.7,122.9,329.1,118.9,54.6,0.4,32.5,35.5
2,Avena,1992/93,BUENOS AIRES,25 DE MAYO,6,854,100,100,100,1000,...,145.6,90.6,219.5,30.7,137.9,355.6,104.3,109.8,3.3,93.2
3,Avena,1994/95,BUENOS AIRES,25 DE MAYO,6,854,500,500,800,1600,...,48.5,122.0,92.0,53.1,94.4,296.0,54.6,19.5,18.1,33.0
4,Avena,1995/96,BUENOS AIRES,25 DE MAYO,6,854,2000,500,1200,2400,...,55.7,69.0,66.8,103.9,28.1,171.3,35.6,1.0,12.2,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23448,Trigo total,2017/18,BUENOS AIRES,ZARATE,6,882,1950,1950,8385,4300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23449,Trigo total,2018/19,BUENOS AIRES,ZARATE,6,882,2800,2800,12320,4400,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23450,Trigo total,2019/20,BUENOS AIRES,ZARATE,6,882,2500,2500,10000,4000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23451,Trigo total,2020/21,BUENOS AIRES,ZARATE,6,882,3000,3000,11700,3900,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23452,Trigo total,2021/22,BUENOS AIRES,ZARATE,6,882,7552,7552,36250,4800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_definitivo['Rendimiento'].replace('SD', '0', inplace=True)
df_definitivo.Rendimiento = df_definitivo.Rendimiento.astype(float)
df_definitivo["Sup_Cosechada"].replace('SD', '0', inplace=True)

In [6]:
df_definitivo["Sup_Cosechada"] = df_definitivo["Sup_Cosechada"].astype(float)

In [7]:
df_definitivo

,Cultivo,Campaña,Provincia,Departamento,idProvincia,idDepartamento,Sup_Sembrada,Sup_Cosechada,Producción,Rendimiento,...,Precipitaciones Noviembre,Precipitaciones Diciembre,Precipitaciones Enero,Precipitaciones Febrero,Precipitaciones Marzo,Precipitaciones Abril,Precipitaciones Mayo,Precipitaciones Junio,Precipitaciones Julio,Precipitaciones Agosto
0,Avena,1987/88,BUENOS AIRES,25 DE MAYO,6,854,3000,1000.0,1800,1800.0,...,117.0,118.5,56.2,32.9,283.0,54.7,0.5,11.6,36.5,35.4
1,Avena,1989/90,BUENOS AIRES,25 DE MAYO,6,854,2000,0.0,0,0.0,...,46.9,193.5,178.7,122.9,329.1,118.9,54.6,0.4,32.5,35.5
2,Avena,1992/93,BUENOS AIRES,25 DE MAYO,6,854,100,100.0,100,1000.0,...,145.6,90.6,219.5,30.7,137.9,355.6,104.3,109.8,3.3,93.2
3,Avena,1994/95,BUENOS AIRES,25 DE MAYO,6,854,500,500.0,800,1600.0,...,48.5,122.0,92.0,53.1,94.4,296.0,54.6,19.5,18.1,33.0
4,Avena,1995/96,BUENOS AIRES,25 DE MAYO,6,854,2000,500.0,1200,2400.0,...,55.7,69.0,66.8,103.9,28.1,171.3,35.6,1.0,12.2,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23448,Trigo total,2017/18,BUENOS AIRES,ZARATE,6,882,1950,1950.0,8385,4300.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23449,Trigo total,2018/19,BUENOS AIRES,ZARATE,6,882,2800,2800.0,12320,4400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23450,Trigo total,2019/20,BUENOS AIRES,ZARATE,6,882,2500,2500.0,10000,4000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23451,Trigo total,2020/21,BUENOS AIRES,ZARATE,6,882,3000,3000.0,11700,3900.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23452,Trigo total,2021/22,BUENOS AIRES,ZARATE,6,882,7552,7552.0,36250,4800.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_definitivo.dropna()

,Cultivo,Campaña,Provincia,Departamento,idProvincia,idDepartamento,Sup_Sembrada,Sup_Cosechada,Producción,Rendimiento,...,Precipitaciones Noviembre,Precipitaciones Diciembre,Precipitaciones Enero,Precipitaciones Febrero,Precipitaciones Marzo,Precipitaciones Abril,Precipitaciones Mayo,Precipitaciones Junio,Precipitaciones Julio,Precipitaciones Agosto
0,Avena,1987/88,BUENOS AIRES,25 DE MAYO,6,854,3000,1000.0,1800,1800.0,...,117.0,118.5,56.2,32.9,283.0,54.7,0.5,11.6,36.5,35.4
1,Avena,1989/90,BUENOS AIRES,25 DE MAYO,6,854,2000,0.0,0,0.0,...,46.9,193.5,178.7,122.9,329.1,118.9,54.6,0.4,32.5,35.5
2,Avena,1992/93,BUENOS AIRES,25 DE MAYO,6,854,100,100.0,100,1000.0,...,145.6,90.6,219.5,30.7,137.9,355.6,104.3,109.8,3.3,93.2
3,Avena,1994/95,BUENOS AIRES,25 DE MAYO,6,854,500,500.0,800,1600.0,...,48.5,122.0,92.0,53.1,94.4,296.0,54.6,19.5,18.1,33.0
4,Avena,1995/96,BUENOS AIRES,25 DE MAYO,6,854,2000,500.0,1200,2400.0,...,55.7,69.0,66.8,103.9,28.1,171.3,35.6,1.0,12.2,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23440,Trigo total,2009/10,BUENOS AIRES,ZARATE,6,882,1430,1430.0,6300,4406.0,...,203.8,312.3,162.0,246.9,81.5,45.0,88.4,42.0,38.9,14.3
23441,Trigo total,2010/11,BUENOS AIRES,ZARATE,6,882,1300,1300.0,5504,4234.0,...,8.2,49.4,198.3,123.5,88.2,98.0,60.3,31.4,29.0,2.3
23442,Trigo total,2011/12,BUENOS AIRES,ZARATE,6,882,1400,1400.0,6160,4400.0,...,131.8,1.1,188.0,233.3,124.0,36.5,122.0,10.5,1.0,10.0
23443,Trigo total,2012/13,BUENOS AIRES,ZARATE,6,882,1320,1320.0,3828,2900.0,...,167.0,150.0,28.0,84.0,279.3,51.1,126.0,18.0,40.2,131.9
23444,Trigo total,2013/14,BUENOS AIRES,ZARATE,6,882,1450,1450.0,5800,4000.0,...,195.2,61.3,188.1,210.5,118.6,188.3,130.8,64.0,17.0,0.0

In [16]:
Girasol = df_definitivo.loc[:, 'Cultivo'] == 'Girasol'
df_G=df_definitivo.loc[Girasol]

In [ ]:
x= df_G.Campaña
y= df_G.Rendimiento
y2= df_G.Precipitacion_Anual
fig, ax = plt.subplots(figsize=(20,6))
ax.bar(x,y)
ax.set_title("Histograma Rendimiento", fontsize=20)
ax.set_xlabel('Campaña',fontsize=15)
ax.set_ylabel('Kg/ha',fontsize=15)
ax.grid(True)
plt.xticks(rotation = 45)
ax2 = ax.twinx()
ax2.plot(x,y2,linewidth=2.0,color='red')

plt.show()